/*
 * This Java source file was generated by the Gradle 'init' task.
 */

  //comentario
  
package MeuPrimeiroProjeto;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println("Olá mundo");
        System.out.println("Meu segundo comando de saida");
    }
}
